### ISSUE TITLE
Version 0.2 RoadMap

### ISSUE THREAD

**Issue by lalo73** [datosgobar/portal-base#3]
Para llegar a la version 0.2 del portal base, se deben cumplir:

- [x] Fijar versiones de las librerias
- [x] Establecer mecanismo de migraciones de ckan minor
- [x] ~Establecer mecanismo de migraciones de ckan patch~
- [x] Establecer migraciones de plugins
- [x] Cambios en migracions

Ademas al finalizar, taguear una version 0.1 de los repos portal-andino y portal_datos.gob.ar

**Comment by lalo73** [comment]
No es necesario un sistema para update patch, ya que segun la documentacion, simplemente hay que instalar, no correr ningun comando, simplemente restartear apache y nginx.

http://docs.ckan.org/en/ckan-2.5.5/maintaining/upgrading/upgrade-package-to-patch-release.html
